name: stockpricerecorder
version: 0.0.1
description: Record stock prices
dependencies:
  browser: any
  shelf: any
  shelf_static: any
  dart_to_js_script_rewriter: any
  http_server: any
transformers:
- dart_to_js_script_rewriter